"""Константы модели пользователя (User)."""
MAX_LENGTH_EMAIL_USER = 250
MAX_LENGTH_USERNAME_USER = 150
MAX_LENGTH_FIRST_NAME_USER = 150
MAX_LENGTH_LAST_NAME_USER = 150
MAX_LENGTH_PATRONYMIC_USER = 150

"""Константы модели цели сбора (Goal)."""
MAX_LENGTH_NAME_GOAL = 250
MAX_LENGTH_SLUG_GOAL = 150

"""Константы модели сбора (Collect)."""
MAX_LENGTH_NAME_COLLECT = 250
MAX_LENGTH_DESCRIPTION_COLLECT = 500