# Generated by Django 4.2.13 on 2024-05-18 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(help_text='Максимальная длинна 250 символов', max_length=250, verbose_name='Название')),
                ('description', models.TextField(help_text='Максимальная длинна 500 символов', max_length=500, verbose_name='Описание')),
                ('total_goal', models.DecimalField(decimal_places=2, default=None, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0, message='Введите значение больше 1.0.')], verbose_name='Необходимая сумма средств сбора')),
                ('is_limited', models.BooleanField(default=True, verbose_name='Сбор ограничен/не ограничен')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Обложка сбора')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения сбора средств')),
            ],
            options={
                'verbose_name': 'Сбор средств',
                'verbose_name_plural': 'Сборы средств',
                'ordering': ('-completion_date',),
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальная длинна 250 символов', max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Максимальная длинна 150 символов', max_length=150, unique=True, verbose_name='Уникальный слаг')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
    ]
