# Generated by Django 4.2.13 on 2024-05-18 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collects.goal', verbose_name='Цель сбора средств'),
        ),
    ]
