# Generated by Django 4.2.13 on 2024-05-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='change_date',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='collect',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания сбора'),
        ),
    ]
