# Generated by Django 4.2.13 on 2024-05-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0003_alter_collect_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='description',
            field=models.TextField(help_text='Максимальная длинна500 символов', max_length=500, verbose_name='Описание'),
        ),
        migrations.RemoveField(
            model_name='collect',
            name='goal',
        ),
        migrations.AddField(
            model_name='collect',
            name='goal',
            field=models.ManyToManyField(blank=True, to='collects.goal', verbose_name='Цель сбора средств'),
        ),
    ]
