# Generated by Django 4.2.13 on 2024-05-17 22:27

import core.mixins
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0, message='Введите значение больше 1.0.')], verbose_name='Сумма пожертвования')),
                ('collect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collects.collect', verbose_name='Сбор')),
            ],
            options={
                'verbose_name': 'Пожертвовавший',
                'verbose_name_plural': 'Пожертвовавшие',
            },
            bases=(models.Model, core.mixins.PublishDateMixin),
        ),
    ]
